security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      user-authorization-uri: http://localhost:9091/oauth/authorize
      access-token-uri: http://localhost:9091/oauth/token
    resource:
      token-info-uri: http://localhost:9091/oauth/check_token
server:
  port: 8083
  servlet:
    session:
      cookie:
        name: BSESSION
